export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const CREATE_INFOS = "CREATE_INFOS";
export const FETCH_USERID = "FETCH_USERID";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const IS_LOGIN = "IS_LOGIN";
export const FETCH_INFO = "FETCH_INFO";
export const UPDATE_NAME =  "UPDATE_NAME";
export const UPDATE_PASSWORD =  "UPDATE_PASSWORD";
export const UPDATE_EMAIL =  "UPDATE_EMAIL";
export const UPLOAD_PROFILE = "UPLOAD_PROFILE";
export const UPLOAD_ARTWORK = "UPLOAD_ARTWORK";
export const GET_ARTWORK = "GET_ARTWORK";
export const GET_ARTWORKBYID = "GET_ARTWORKBYID"

